-- ════════════════════════════════════════════════════════════════════════════
-- BƯỚC CUỐI: ĐẨY PHIÊN BẢN NỘI DUNG — viết tay, KHÔNG do script sinh.
--
-- VÌ SAO PHẢI CÓ FILE NÀY (lỗi âm thầm nếu thiếu):
--   Các file `0X-bai-lop-*.sql` chỉ GHI bài vào bảng. File `99-...` chỉ đặt
--   `content_version = 1` KHI ĐANG NHỎ HƠN 1 (cố ý, để chạy lại không kéo lùi
--   phiên bản admin đã publish). Nghĩa là chạy lại seed KHÔNG làm phiên bản tăng
--   ⇒ máy các bé vẫn dùng cây đã cache và KHÔNG BAO GIỜ thấy bài mới.
--   App chỉ tải lại nội dung khi `content_version` đổi. Bước này bù đúng chỗ đó.
--
-- KHI NÀO CHẠY: sau khi dán lại seed, mỗi lần nội dung thay đổi. Chạy SAU cùng.
-- CHẠY LẠI NHIỀU LẦN: chỉ làm phiên bản tăng thêm 1 mỗi lần — vô hại (các bé tải
--   lại nội dung thêm một lần), không sinh dòng trùng, không mất dữ liệu.
--
-- LƯU Ý LẦN 26 (2026-09-29): **BỔ SUNG 1 847 SLIDE CHO CẢ 489 BÀI — KHÔNG CÒN BÀI DƯỚI KHUNG**.
--   Người dùng gửi ảnh màn hình bài `g2-c4-l1` và báo: *“1 chủ đề quan trọng như bài 1 chủ đề 4 lớp 2
--   mà phần học lại sơ sài vài slide, giải thích thì không rõ ràng”*. Đo cả 5 lớp thì đây là lỗi
--   HỆ THỐNG: **469/489 bài** dưới khung tối thiểu (≥8 slide · ≥2 hình · ≥1 slide chỉ TỪNG BƯỚC ·
--   ≥700 ký tự diễn giải). Công cụ đo: `scratch/soat-bai-mong.mjs`.
--
--   QUY MÔ ĐỔI: **3163 → 4987 slide** (5 lớp · 65 chương · 489 bài KHÔNG đổi). Số bài dưới khung:
--     **469 → 0**. Dấu vân tay seed: `95a9ad9f8051ed80` → **`71b5da8ec6e9ea54`**.
--     Lớp 1: 733→1115 · Lớp 2: 717→1141 · Lớp 3: 771→1223 · Lớp 4: 489→769 · Lớp 5: 453→739.
--
--   SỬA LỖI CHẤT LƯỢNG (người dùng gửi 3 ảnh bài “Tiết học đầu tiên”, cùng ngày) — 4 họ lỗi, đã sửa cả 4:
--     • (A) **Dạy trước chương trình**: bài chưa học số nào mà đã có “Số nào LỚN NHẤT trong 1, 6, 7?”
--       và “Số liền sau của số 1”. Nay bài định hướng được nhận diện và KHÔNG sinh nội dung số.
--     • (B) **Ngoài phạm vi bài**: bài lịch bị gắn bảng giờ–phút–giây và nói SAI “1 tháng = 30 ngày”
--       (thật ra tháng có 30 hoặc 31 ngày; tháng 2 có 28/29) ⇒ lịch và tiền chuyển sang BẢNG SỰ KIỆN.
--     • (C) **Sai mức độ**: hai số MỘT chữ số mà dạy “đếm số chữ số” ⇒ số ≤ 10 dạy so sánh bằng ĐẾM.
--     • (D) **Lỗi chữ**: “hình tròn có không có cạnh”, “đoạn thẳng có có hai đầu mút”, dấu “…” trong câu.
--     • Thêm: **số trang sách** (“(SGK tr.14–17)”) bị đếm thành số của bài ⇒ đã lọc bỏ.
--     • Công cụ soi mới: `scratch/soat-noi-dung-tu-sinh.mjs` (so với bản gốc trong git) ⇒ A = B = C = 0.
--
--   BỐN LƯỢT SINH (script chạy lại được, tự bỏ qua bài đã có — xem `scratch/bo-sung-*.mjs`):
--     • Lượt 1 `bo-sung-tu-dong.mjs` — bài có phép tính: đặt tính tương tác (`cotTinh`, bé điền cả ô
--       “nhớ”) + lời giải từng hàng SINH TỪ `buocTinh()` (không viết tay nên không thể lệch số) +
--       slide “lỗi hay gặp” với con số sai TÍNH RA bằng thuật toán sai thật (quên nhớ 1 · quên trả
--       1 chục · quên nhớ khi nhân) + câu luyện cùng dạng, đáp án nhiễu chính là kết quả làm sai đó.
--     • Lượt 2 `bo-sung-khai-niem.mjs` — số (tách hàng bằng `baseTen`/`placeValue`), hình học (vẽ
--       ĐÚNG hình của bài: hình phẳng có chấm đỉnh, khối, điểm–đoạn thẳng, góc), đo lường (bậc thang
--       đơn vị với hệ số TỪNG BƯỚC), bảng nhân/chia, thống kê (bảng số liệu LẤY TỪ CHÍNH BÀI), phân số.
--     • Lượt 3 `bo-sung-bai-on-tap.mjs` — “bốn bước làm một bài toán” + “bảng nhớ nhanh” + câu hỏi
--       quy trình, cho nhóm bài khái niệm/ôn tập còn lại.
--     • Lượt 4 `bo-sung-lap-khoang-trong.mjs` — tia số có cung nhảy (đếm thêm – làm tròn chục, hoặc
--       đếm thêm để tìm hiệu) + bảng ba bước + câu luyện, cho 88 bài còn thiếu 1 slide/1 hình.
--
--   CHUẨN SƯ PHẠM ĐÃ TRA VÀ ÁP DỤNG (ghi ở `docs/ke-hoach-bo-sung-bai-hoc.md`): trình tự CPA
--   (cụ thể → hình ảnh → trừu tượng: khối chục–đơn vị cho bé THẤY vì sao phải nhớ 1), chiến lược
--   làm tròn chục / đếm thêm (Singapore Math, Eureka/EngageNY, chương trình Anh KS1–KS2), và dạy
--   bằng phân tích lỗi (đáp án nhiễu chính là lỗi trẻ thật sự mắc).
--
--   ⚠️ Chữ thô kiểu “  27 / +  5 /  32” ở các slide cũ đã đổi thành tiêu đề + lời giải từng bước.
--   ⚠️ Các slide `visual` cũ có `placeValue.label` TRÙNG với lời giải từng bước đã bỏ nhãn — luật
--     `slideDedupe.planVisualText` sẽ BỎ dòng nào mà hình đã nói lại, nên giữ nhãn là mất lời giải.
--
--   CÔNG CỤ MỚI: `scratch/soat-bai-mong.mjs` (đo độ mỏng từng bài) · `scratch/ke-hoach-dot-bo-sung.mjs`
--     (gom lên cấp chương) · `scratch/lib-chen-slide.mjs` (thư viện chèn slide dùng chung cho 4 lượt) ·
--     `scratch/kiem-tra-ngoac.mjs` (soi lệch ngoặc theo độ thụt lề — một dấu `}` thừa làm `node` chỉ
--     báo lỗi ĐẦU TIÊN, sửa xong mới lộ lỗi sau; công cụ này chỉ đúng ca gốc trong MỘT lượt).
--   📌 CÒN LẠI (không phải “dưới khung”): `cotTinh` chưa vẽ dấu “mượn” cho phép trừ; nên soát bằng
--     mắt vài bài mẫu mỗi nhóm trên điện thoại; nhóm hình học chưa có hoạt ảnh cắt ghép.
--
-- LƯU Ý LẦN 27 (2026-09-29): **APP THÀNH APP ĐỘC LẬP + BỎ “COMBO x N”**. Hai yêu cầu của người dùng:
--   (1) *“bỏ phần hiện combo khi bé làm đúng liên tiếp”* — banner `🔥 COMBO x{combo}` ở đầu trang bài
--       học đã bỏ hẳn (JSX + state + CSS), KHÔNG đụng phần thưởng xu/XP (vẫn theo `reward_configs`).
--       *Lưu ý:* phần “Combo” trong **trò chơi bắn thiên thạch** (`GamesPage`) là luật TÍNH ĐIỂM của
--       trò chơi đó, không phải banner động viên — vẫn giữ.
--   (2) *“bỏ hết tất cả các text có đề cập đến sách giáo khoa… để trở thành 1 app độc lập”* — nhãn dẫn
--       sách **xoá khỏi chính DỮ LIỆU**, không chỉ ẩn lúc hiển thị nữa:
--         • 116 dòng trong 9 file dữ liệu: `(SGK tr.6)`, `SGK Bài 2 (tr.14–17): …`, `— bảng như SGK tr.4`,
--           `(tr.10, tr.16)`, `theo đúng SGK.` ⇒ bỏ nhãn, giữ nguyên phần chữ có nghĩa.
--         • Bài định hướng Lớp 1 viết lại theo CHÍNH APP: “Mỗi bài học thường có bốn phần nào?”
--           (Khám Phá · Thực Hành · Luyện Tập · Trò Chơi) và “Bé học Toán như thế nào?” chỉ đúng
--           giao diện thật (số trang ở góc trên bên phải · nút “Trước”/“Tiếp tục” · nút loa · gợi ý
--           của Rô-bốt). Bản cũ nói về “mở sách đúng trang”, “sách Toán 1” — app không có sách giấy.
--         • 81 dòng ghi chú mã nguồn trong 23 file: “cách SGK dạy” ⇒ “cách dạy”, “SGK Lớp 3–4” ⇒ “Lớp 3–4”…
--         • Bộ lọc `client/src/utils/stripTextbookRefs.js` **VẪN GIỮ** làm lưới an toàn: cây cũ trong
--           DB hoặc cache `localStorage` của máy bé còn nhãn thì vẫn không lộ ra giao diện (cổng S-33).
--
--   QUY MÔ: **4987 slide KHÔNG đổi** (5 lớp · 65 chương · 489 bài). Chỉ nội dung chữ đổi.
--     Dấu vân tay seed: `71b5da8ec6e9ea54` → **`cfa96b289a8e0220`**.
--
--   ⚠️ BÀI HỌC CỦA CHÍNH LẦN NÀY: máy xoá nhãn áp luật `.*$` cho cụm “— bảng như SGK tr.4” nên ăn
--     LUÔN dấu nháy đóng của chuỗi ⇒ `g1c6.js` hỏng cú pháp, mà phép kiểm lại ĐỒNG Ý vì bản “đích”
--     cũng dựng bằng đúng luật sai đó (thước sai y như mã sai). Nay có thêm bước kiểm CÚ PHÁP thật
--     (`import()` từng file dữ liệu) trong quy trình.
--
-- LƯU Ý LẦN 25 (2026-09-28): **HAI DẠNG BÀI “TỰ TRẢ LỜI”** (ảnh Duolingo thứ hai).
--   Người dùng gửi thêm hai ảnh Duolingo: (1) “Nhập câu trả lời” — `4 + 4 + 4 + 4 = ☐` kèm BÀN PHÍM
--   SỐ để bé tự gõ; (2) “Trả lời trên trục số” — KÉO CON TRỎ trên tia số. Nay Toán Vui có cả hai.
--
--   QUY MÔ ĐỔI: **3157 → 3163 slide** (thêm 6 slide ở 6 bài; 5 lớp · 65 chương · 489 bài KHÔNG đổi).
--     • `typeAnswer` (nhập kết quả): g1-c3-l9 (`10 − 6 =` → 4), g2-c8-l6 (`2 × 7 =` → 14),
--       g3-c4-l2 (`24 × 3 =` → 72).
--     • `numberLineAnswer` (trục số): g2-c8-l4 (`2 + 2 + 2 = 3 ×` → 6), g3-c8-l7 (`47 ≈` → 50),
--       g4-c3-l4 (`4 600 ≈` → 5 000).
--
--   BỐ CỤC — giữ ĐÚNG luật đã rút ra ở LẦN 24: hàng trên là KHUNG MẪU (số cho trước / phép tính +
--   MỘT hộp TRỐNG, không bao giờ hiện dữ liệu bé chọn); dữ liệu bé nhập hiện ở khu vực riêng dưới.
--     • `typeAnswer`: ô hiện số bé gõ + bàn phím 1–9 · 0 · ⌫ + nút KIỂM TRA (mờ tới khi bé gõ).
--     • `numberLineAnswer`: trục số có nhãn BẤM ĐƯỢC + con trỏ KÉO ĐƯỢC (bàn phím ← → cũng chạy)
--       + nút KIỂM TRA (mờ tới khi bé chọn vạch).
--   Ba dạng bài dùng CHUNG một khối CSS khung phép tính (`.expr-frame`) nên không thể lệch nhau.
--
--   🔴 LUẬT CHỐNG “BÀI VÔ NGHIỆM” (đúng họ lỗi im lặng của LẦN 24):
--     • `expression` KHÔNG được kết thúc bằng chữ số (hộp mẫu nối ngay sau nó);
--     • `answer` phải là số TỰ NHIÊN (bàn phím không có dấu phẩy / dấu trừ);
--     • trục số: `step` phải chia hết khoảng, và **`answer` PHẢI nằm đúng trên một vạch** — không
--       thì bé kéo đúng cỡ nào cũng không chạm tới đáp án; số vạch từ 2 đến 7 để mỗi ô bấm đủ lớn.
--   ⇒ Chặn bằng ba lớp như LẦN 24: (a) form Admin báo lỗi ngay khi soạn; (b) `migrate-content.mjs`
--     chặn lúc GHI (dùng lại chính `ticksOf` của app); (c) cổng `kiem-tra-slide.mjs` + unit test.
--   ⚠️ Canary bắt được một lỗi THẬT ngay lượt đầu: luật “nằm đúng trên vạch” viết thiếu `Math.abs`
--     nên MỌI giá trị nằm dưới vạch đều lọt — đã sửa và có test hai vế.
--
--   ✅ ĐÃ ĐO TRONG APP: 390 px và 320 px — 0 tràn ngang; bàn phím số mỗi ô 48–49 px; nhãn trục số
--      cao 45 px (lần đo đầu chỉ 43 px nên đã nâng lên 46 px, đúng ngưỡng bấm của trẻ); kéo con trỏ
--      bám đúng vạch gần nhất, bấm nhãn cũng chọn được; chấm đúng/sai đổi màu ô + con trỏ.
--
--   📌 PHẢI DÁN LẠI SEED — nội dung ĐÃ ĐỔI ở 4 lớp (1, 2, 3, 4):
--      `02-bai-lop-1.sql` → `03-bai-lop-2.sql` → `04-bai-lop-3.sql` → `05-bai-lop-4.sql`
--      → `06-bai-lop-5.sql` → rồi file NÀY (`100-...`) để đẩy `content_version`.
--
-- LƯU Ý LẦN 24 (2026-09-28): **BA DẠNG BÀI MỚI KIỂU DUOLINGO + SỬA LUẬT THẺ GHÉP**.
--   Người dùng gửi ảnh Duolingo Math và nhờ "phân tích và áp dụng vào phần bài học, luyện tập,
--   trò chơi". Đợt này THÊM 8 SLIDE mới vào 8 bài (lớp 1, 2, 3, 4, 5 đều có), nên QUY MÔ ĐỔI:
--   **3149 → 3157 slide** (5 lớp · 65 chương · 489 bài GIỮ NGUYÊN).
--
--   BA DẠNG MỚI (luật chấm ở `client/src/pages/lesson/answerLogic.js`, có unit test riêng):
--     • `multiQuiz`       — "Chọn TẤT CẢ các phương án thích hợp": bé bấm nhiều ô rồi KIỂM TRA.
--       Đúng khi chọn ĐỦ và KHÔNG THỪA. Sai thì tô riêng từng ô (đỏ = chọn sai, viền đứt =
--       bỏ sót), KHÔNG tô đỏ cả câu.
--     • `buildExpression` — ghép thẻ thành phép tính đúng cho trước kết quả (`100 = ☐ ☐ ☐`).
--     • `matchPairs`      — nối cặp (dạng "Nối theo mẫu" rất phổ biến trong SGK Lớp 1–3). Cột
--       phải tự ĐẢO vòng để bé không chỉ việc nối hàng trên với hàng dưới.
--   Kèm theo: huy hiệu **COMBO** khi bé làm đúng liên tiếp trong cùng một bài.
--
--   🔴 BÀI HỌC ĐẮT NHẤT CỦA ĐỢT NÀY — THẺ GHÉP KHÔNG ĐƯỢC TRỘN SỐ VỚI DẤU (người dùng bắt lỗi):
--      Bản đầu tôi soạn khay `["25 ×", "4", "5", "20 ×", "6"]` — dấu DÍNH vào số. Người dùng hỏi
--      thẳng: *"phép nhân phải để riêng thành 1 ô chứ sao lại kèm vào số? thế tôi muốn 4 × 25
--      thay vì 25 × 4 thì sai à?"* — ĐÚNG CẢ HAI VẾ:
--        1. Với khay đó bé **KHÔNG THỂ** ghép `4 × 25`: trong khay không có thẻ `"25"` rời, cũng
--           không có thẻ `"×"` rời. Bài chỉ còn ĐÚNG một đường đi do người soạn vạch sẵn.
--        2. Luật chấm cũ so CHUỖI với `solutions`, nên `4 × 25` bị báo SAI dù đúng toán học.
--      ⇒ Nay mỗi thẻ là MỘT số (`"25"`, `"1 000"`, `"0,5"`) hoặc MỘT dấu (`"+"`, `"−"`, `"×"`, `":"`),
--        và chấm theo GIÁ TRỊ (`matchesTarget`) — `25 × 4` và `4 × 25` đều đúng, KHÔNG phải kê
--        từng hoán vị vào `solutions` (kê thiếu một hoán vị là bé làm đúng mà bị báo sai).
--      ⇒ Chặn bằng BA lớp, không chỉ một:
--        (a) `admin/src/lib/contentSchema.js` — báo lỗi NGAY khi soạn: thẻ phải là một số HOẶC
--            một dấu, khay phải có thẻ dấu, `target` phải đọc được thành số;
--        (b) `scripts/migrate-content.mjs` — chặn lúc GHI: mỗi cách trong `solutions` phải TÍNH
--            RA đúng `target`, nếu không thì bài vô nghiệm (bé tính đúng vẫn báo sai);
--        (c) `scratch/kiem-tra-slide.mjs` + canary HAI VẾ trong cổng S-23 (bắt được thẻ trộn,
--            và KHÔNG báo oan khay thẻ tách rời).
--      ⚠️ Mẫu slide mới trong trình soạn bài (`admin/src/lib/soanBai.js`) cũng đã đổi theo.
--
--   ✅ ĐÃ ĐO TRONG APP (390 px · 0 tràn ngang · ô bấm ≥ 44 px):
--      • `g2-c8-l15` ghép `4 × 25` → 🎉 đúng (trước đây không thể ghép được);
--      • `g4-c8-l11` ghép `8 × 125` → 🎉 đúng (trước đây báo sai) và `4 × 25` (=100 ≠ 1 000) → 😅;
--      • `g1-c3-l13` nối cặp: nối sai thì nháy đỏ + không tăng tiến độ, xong 3/3 mới mở khoá;
--      • COMBO x2 hiện đúng sau 2 câu trả lời đúng liên tiếp.
--
--   ✅ LẦN SỬA THỨ HAI CỦA CÙNG NGÀY — BỐ CỤC (người dùng gửi ảnh thật của Duolingo):
--      Tôi đã hiểu SAI hai lần. Lần 1: để dấu dính vào số (`"25 ×"`) ⇒ bé không ghép được `4 × 25`.
--      Lần 2: nhồi `1 000 = ☐ ☐ ☐` vào MỘT hàng rồi ÉP không cho xuống dòng ⇒ sai tiếp.
--      Ảnh Duolingo cho thấy họ TÁCH HAI HÀNG. Nay `buildExpression` làm đúng vậy:
--        (1) hàng ĐẠI DIỆN `1 000 = [ hộp ]` — hộp chỉ là KHUNG MẪU, LUÔN ĐỂ TRỐNG;
--        (2) hàng Ô TRỐNG nằm DƯỚI, mỗi số/ký tự cần điền là MỘT ô — đây mới là chỗ hiện
--            số/ký tự bé đã chọn;
--        (3) khay thẻ — thẻ ĐÃ DÙNG thành Ô XÁM TRỐNG (giữ nguyên vị trí, khay không nhảy chỗ);
--        (4) nút KIỂM TRA (mờ cho tới khi điền đủ ô — bỏ kiểu tự chấm khi vừa đủ ô).
--      Vì sao đúng: hàng (1) chỉ có hai thứ cố định + một hộp nên KHÔNG BAO GIỜ vỡ; hàng (2) muốn
--      bao nhiêu ô cũng được. Câu hỏi của hai bài ghép thẻ cũng được RÚT NGẮN
--      ("Ghép phép nhân có tích bằng 100 / 1 000"). Đã đo ở 360/390/430 px: 0 tràn ngang.
--      (Chỉ đổi MÃ + lời văn câu hỏi, không đổi luật chấm.)
--
--   📌 PHẢI DÁN LẠI SEED — nội dung ĐÃ ĐỔI ở CẢ 5 LỚP (mỗi lớp được thêm slide mới):
--      `02-bai-lop-1.sql` → `03-bai-lop-2.sql` → `04-bai-lop-3.sql` → `05-bai-lop-4.sql`
--      → `06-bai-lop-5.sql` → rồi file NÀY (`100-...`) để đẩy `content_version`.
--      Dán thiếu file của lớp nào thì lớp đó KHÔNG có dạng bài mới (bài cũ vẫn hiện bình thường).
--
-- LƯU Ý LẦN 23 (2026-09-28): **ĐÁP ÁN TRẮC NGHIỆM CĂN TRÁI** (sửa lại luật của LẦN 21).
--   Người dùng gửi ảnh một câu hỏi có 4 phương án là CÂU CHỮ và nói rõ: *"câu trả lời căn giữa
--   quá xấu và không phù hợp"* + *"kiểm tra các câu trả lời phải căn trái, rà soát lại tất cả các
--   bài học, luyện tập, trò chơi"*.
--
--   🔴 LUẬT 1 CỦA LẦN 21 ĐÃ SAI Ở CHỖ "PHƯƠNG ÁN" — nay tách thành hai vai trò khác nhau:
--      • ĐÁP ÁN TRẮC NGHIỆM (`pages/LessonPage.css`) → **căn TRÁI**. Đoạn chữ canh giữa thì mỗi
--        dòng một mốc, mắt trẻ phải dò lại đầu câu; canh trái thì MỌI phương án bắt đầu ở cùng
--        một mốc (ngay sau vòng tròn A/B/C/D) và ngọn cờ ✔/✗ được đẩy ra mép phải.
--      • NGOẠI LỆ DUY NHẤT: hàng **3 ô chỉ chứa ký hiệu** `>` `<` `=` (lớp `quiz-options-3`)
--        GIỮ căn giữa — ký hiệu đối xứng, không phải câu để đọc.
--      • ĐÁP ÁN bên **Luyện tập / Sổ Tay Ôn Bài Sai**: chỉ đáp án **CÓ CHỮ** mới căn trái
--        ("3 nghìn, 5 trăm, 1 chục, 7 đơn vị"); đáp án SỐ/KÝ HIỆU giữ căn giữa. Luật nằm ở
--        MỘT nguồn duy nhất: `client/src/utils/answerAlignment.js` (`isTextAnswer`), có unit test.
--      • **Trò chơi / Thử thách / Truyện / Đố vui trong bong bóng linh vật**: đáp án là SỐ
--        (mã laser, bóng bay, cân thăng bằng, vạch xuất phát) ⇒ KHÔNG đổi, vì căn trái một con số
--        trong ô to sẽ lệch và xấu hơn. Đã rà: 0 chỗ nào có đáp án chữ.
--      • Slide "hội thoại" (`dialogue`): dữ liệu hiện KHÔNG có slide nào kèm `options` ⇒ không đổi.
--
--   ✅ Cổng S-36 đã cập nhật theo luật mới: `.quiz-option` và `.quiz-option-text` phải căn TRÁI,
--      `.quiz-options-3 .quiz-option` phải GIỮ căn giữa, `.practice-opt-btn.is-text-answer` VÀ
--      khối chữ `.opt-val-text` bên trong nó cũng phải căn TRÁI, và cổng canh luôn sự tồn tại của
--      `utils/answerAlignment.js` + việc `PracticePage.jsx` dùng nó (một nguồn luật, không chép tay).
--      🔴 Vì sao phải kiểm CẢ KHỐI CHỮ: `.opt-val-text` tự khai `text-align: center`, nên chỉ đặt
--      `text-align: left` ở cái nút là chưa đủ — đáp án dài hai dòng vẫn canh giữa. Đây đúng họ lỗi
--      "hai vế" đã gặp ở slide câu hỏi, nên cổng kiểm cả hai vế cho cả hai màn hình.
--   ✅ Đo TRONG APP ở 390 px: 4 đáp án chữ của `g1-c1-l1` slide 5 bắt đầu cùng mốc **x = 80 px**,
--      `text-align: left`; quiz 3 dấu `>` `<` `=` vẫn `center`; **0 tràn ngang**.
--   ⚠️ **KHÔNG cần dán seed lần này** — đây là phần **MÃ**. `content_version` không đổi.
--      Muốn thấy trên máy các bé thì **deploy web** (Vercel) và **build APK** lại.
--
-- LƯU Ý LẦN 22 (2026-09-28): **DỰNG LẠI TOÀN BỘ LỚP 4 VÀ LỚP 5 THEO SÁCH KẾT NỐI TRI THỨC**.
--   Người dùng yêu cầu: *"tôi cần bạn bỏ hết nội dung lớp 4 và lớp 5 hiện tại, thay đổi chuẩn hoá theo tài
--   liệu mới nhất"* — bỏ HOÀN TOÀN nội dung sách cũ (bộ Đỗ Đình Hoan trước 2018) và viết lại theo bộ
--   **Kết nối tri thức với cuộc sống**, cả hai tập của mỗi lớp.
--
--   🔴 VÌ SAO PHẢI LÀM LẠI TỪ ĐẦU: nội dung Lớp 4–5 cũ bám sách cũ (6 chương Lớp 4, 5 chương Lớp 5) nên
--      thứ tự bài, tên chủ đề, cách dạy đều KHÁC sách bé đang học trên lớp ⇒ bé mở app không tìm được bài
--      cô giao. Nguồn mới: `docs/DataSource/Grade 4|5/Math grade 4|5 part 1|2.pdf`.
--
--   📌 QUY MÔ MỚI (đo bằng `node scratch/kiem-tra-slide.mjs`):
--      • Cả hệ thống: 5 lớp · **65 chương** · **489 bài** · **3149 slide**.
--      • Lớp 4: 13 chủ đề · 73 bài · 486 slide (trước: 6 chương · 37 bài).
--      • Lớp 5: 12 chủ đề · 75 bài · 452 slide (trước: 5 chương · 54 bài).
--      • Lớp 1–3 giữ nguyên (10/16/16 chương — 731/713/767 slide).
--
--   🔴 MÃ BÀI HỌC ĐỔI HẾT Ở LỚP 4–5 (`g4-c8-l1` … `g4-c13-l7`, `g5-c1-l1` … `g5-c12-l7`): người dùng đã
--      chốt *"dùng mã bài hoàn toàn mới, chấp nhận mất tiến độ của các bé ở Lớp 4–5"*. Vì vậy:
--        • phải chạy `00-don-noi-dung-cu.sql` TRƯỚC khi dán seed — nếu không, bài cũ (chủ đề sai) VẪN
--          hiện trên app vì seed chỉ upsert, không xoá;
--        • tiến độ/điểm của các bé ở bài Lớp 4–5 cũ không còn gắn với bài nào (đúng như đã chốt).
--
--   ⚠️ BÀI HỌC CỦA LẦN NÀY (đều là lỗi suýt lọt, đã có cổng chặn):
--      1. Trong ô bảng, dấu ba chấm `…` bị hiểu là "ô trống cần điền" ⇒ cổng `soat-o-trong` báo đỏ:
--         thay `278 992 000 … 278 999` bằng `278 992 000 và 278 999`.
--      2. Viết chuỗi biểu thức nối tiếp (`7 200 : 40 = 720 : 4 = 180`) làm cổng `soat-phep-tinh` hiểu
--         sai vế ⇒ nay viết thành từng bước đơn giản, mỗi bước một dấu bằng.
--      3. Số đếm quy mô nằm rải rác ở 5 chỗ (`migrate-content.mjs` MONG_DOI, `test-admin-portal.mjs`
--         S-15 ×2 + S-23 + S-24, hai file docs, chính file này) ⇒ đã cập nhật hết về 65/489/3149.
--      4. Cổng S-15 canh "số KIỂU slide" — nội dung mới chỉ dùng 5 kiểu (story/visual/concept/quiz/
--         summary) nên con số canh đã đổi từ 6 về 5.
--
--   Thứ tự dán (đúng như vậy, không đổi): `00` → `01` → `02` → `03` → `04` → `05` → `06` → `99` → file này.
--
-- LƯU Ý LẦN 21 (2026-09-27): CĂN LỀ THEO VAI TRÒ · BẢNG DÙNG HẾT KHUNG · BỎ CHỮ TRÙNG.
--   Người dùng gửi 3 ảnh và yêu cầu rõ: *"hãy rà soát tất cả bài học ở 5 lớp chứ không phải chỉ 1 bài
--   học mà tôi gửi ảnh, rà và điều chỉnh lại hết cho đồng bộ hệ thống"*.
--     (1) Ảnh 1 — slide "Làm quen" Lớp 1 Bài 1: nội dung trong khung đỏ BỊ TRÙNG LẶP.
--     (2) Ảnh 2 — slide "Quan sát": khung bảng còn trống hai bên mà chữ vẫn bị xuống dòng.
--     (3) Yêu cầu chung: phân tích căn GIỮA hay căn TRÁI cho TỪNG loại khối, không áp một kiểu cho hết.
--
--   🔴 CĂN LỀ THEO VAI TRÒ (chốt trong `client/src/pages/LessonPage.css`, mục "LUẬT CĂN LỀ"):
--      1. tiêu đề · câu hỏi · phương án · nhãn · chú thích hình  → căn GIỮA
--      2. đoạn văn xuôi (câu giải thích · câu chốt · lời thoại linh vật · mô tả thẻ hình) → căn TRÁI
--      3. danh sách (gạch đầu dòng, ô ghi nhớ) → căn TRÁI, biểu tượng canh theo DÒNG ĐẦU
--      4. bảng → theo CỘT: cột giá trị (số, số La Mã) căn GIỮA · cột chữ căn TRÁI
--      ⚠️ Đã thử "căn theo ĐỘ DÀI đoạn chữ" rồi BỎ: cùng 50 ký tự là một dòng trên máy tính nhưng hai
--         dòng trên điện thoại ⇒ ngưỡng ký tự cho hai kiểu căn khác nhau tuỳ máy. Luật theo VAI TRÒ mới
--         giống nhau ở mọi kích thước màn hình. Cổng tĩnh mới **S-36** canh đúng bốn dòng luật này.
--
--   🔴 BẢNG DÙNG HẾT KHUNG + KHÔNG TỰ XUỐNG DÒNG OAN (`components/visuals/tableAlignment.js`):
--      • Cột rộng vừa đủ nội dung dài nhất nhưng số ký tự mỗi dòng tính bằng `floor()` **hụt đúng
--        1 ký tự** ⇒ "Hoạt động" tự xuống dòng dù ô còn chỗ. Nay `charsPerLine()` = min(độ dài dài
--        nhất, số suy từ bề rộng).
--      • Bảng ≤ 3 cột nay GIÃN cho dùng hết ngân sách 368 đơn vị. Đo trong app: khung bảng lấp
--        **93% bề rộng thẻ hình** (trước 76%) ⇒ hết cảnh khung lọt thỏm giữa thẻ.
--      • Bảng ĐIỀN ĐƯỢC (`bangTinh`) CỐ Ý KHÔNG giãn: hàng 56 đơn vị mà giãn khung thì trên điện thoại
--        ô bấm tụt dưới chuẩn 44 px. Cổng S-36 chặn việc "cho đồng bộ" này.
--
--   🔴 BỎ CHỮ ĐÃ BỊ NÓI LẠI — luật HIỂN THỊ, dữ liệu không bị sửa (`pages/lesson/slideDedupe.js`):
--      • Slide khái niệm: bỏ ô nhấn mạnh khi danh sách bên dưới đã nói đủ (**21 ca**), bỏ câu giải
--        thích khi ô nhấn mạnh đã nói đủ (**5 ca**). Lời đọc thành tiếng cũng chỉ đọc phần đang hiện.
--      • Slide "Quan sát": bỏ dòng `text` mà HÌNH trên cùng slide đã chứa trọn (**115 ca**), và
--        **177 ca** lấy NHÃN của hình làm tiêu đề rồi bỏ nhãn đó dưới hình (tiêu đề vẫn có, mà không
--        nói hai lần). Nguyên nhân họ lỗi này: các lần "bổ sung hình minh hoạ" thêm bảng vào slide
--        ĐÃ có bản chữ nhưng không xoá bản chữ cũ.
--      ℹ️ Đây là luật hiển thị nên áp cho CẢ NĂM LỚP ngay sau khi deploy — không phải dán 5 file seed.
--
--   THÊM (cùng ngày, sau khi người dùng CHỐT "hãy ẩn ô đó"): phần VẼ đã ẩn mà phần ĐỌC TỰ ĐỘNG
--      (`autoSpeakLesson`) VẪN đọc ô nhấn mạnh và câu giải thích đã bị ẩn ⇒ trên màn hình không có
--      chữ mà loa vẫn đọc, bé nghe đúng một thông tin hai lần; slide "Quan sát" cũng bị đọc cả dòng
--      đã bỏ vì hình nói lại. Nay chỉ còn MỘT nguồn luật: `slideDedupe.planConceptText` (phần vẽ),
--      chữ để đọc do hàm thuần `utils/slideSpeech.planSlideSpeech` quyết định, `LessonPage` chỉ gọi
--      hàm đó — hết cảnh hai nơi tự quyết định rồi lệch nhau.
--      Cổng tĩnh mới **S-37** canh đủ 3 mắt xích (canary HAI VẾ: vế 1 chứng minh cổng bắt được mã cũ
--      đọc thẳng `s.content.rule`, vế 2 chứng minh không bắt oan mã mới).
--      Dạy quy tắc để không tái phạm: **màn hình hiện chữ nào thì loa đọc chữ đó**.
--      Quy mô KHÔNG đổi: 5 lớp · 51 chương · 460 bài · 2814 slide. Đây là phần MÃ.
--
--   📌 PHẦN DỮ LIỆU CỦA LẦN NÀY RẤT NHỎ: chỉ `g1-c1-l1` slide 3 bỏ mảng `points` (bốn dòng lặp lại
--      ô nhấn mạnh) — slide đó nay GIỚI THIỆU tên bốn biểu tượng, slide sau mới giải nghĩa từng cái.
--      Chỉ cần dán `02-bai-lop-1.sql` rồi `100-...`.
--   ⚠️ Quy mô KHÔNG ĐỔI: 5 lớp · 51 chương · **460 bài · 2814 slide**.
--   ⚠️ Phần MÃ (`LessonPage.css`, `conceptSlide/storySlide/visualSlide`, `CoreVisuals`,
--      `interactiveTable`, `textCompare`, `slideDedupe`) thì dán SQL KHÔNG thấy — phải deploy web /
--      build APK lại.
--   ✅ Kiểm: cổng tĩnh **35 PASS · 0 FAIL** · `npm test` **83/83** · `oxlint` sạch ·
--      `kiem-tra-slide` 0 lỗi · `soat-o-trong` 0 ca · `ra-hinh-nghi-ngo` 0 ca ·
--      `node scratch/soat-an-o-nhan-manh.mjs` 6/6 ca đo TRONG APP (4 ca phải ẩn + 2 ca phải hiện).
--

-- LƯU Ý LẦN 20 (2026-09-26): **TÁCH “SLIDE DỒN NHIỀU BÀI” + LỜI GIẢI TỪNG BƯỚC**.
--   Người dùng báo (kèm ảnh `g3-c7-l1`): *“slide quá chung chung, không hướng dẫn cũng như chỉ cho
--   bé thấy làm sao để ra kết quả; gộp nhiều phép tính vào 1 slide gây rối, tại sao không tách ra
--   và giải thích từng bước?”*
--   • 19 slide kiểu “bảng Phép tính | Kết quả” (mỗi dòng một BÀI KHÁC NHAU) đã tách thành
--     **53 slide** — mỗi bài một slide, có **lời giải từng hàng** (nhớ · mượn · hạ · tích riêng)
--     và **hình cho bé tự điền** (`cotTinh`; bài không vẽ được cột thì dùng `bangTinh`).
--   • Lời giải do `client/src/components/visuals/columnSteps.js` SINH TỰ ĐỘNG từ chính con số ⇒
--     không thể lệch với kết quả; cổng `scratch/kiem-tra-buoc-tinh.mjs` 33/33 (canary hai vế).
--   • Đúng cách dạy SGK: nhân/chia với 10, 100, 1 000 dạy MẸO thêm/bớt chữ số 0, không dùng tích riêng.
--   • MÃ cũng đổi: slide “Quan sát” nay vẽ **dòng đầu của `text` là TIÊU ĐỀ**, phần còn lại là đoạn
--     lời giải (`.slide-visual-steps`) — trước đây cả khối bị dồn vào `<h2>`.
--   • 🔴 SỬA THỨ TỰ Ô ĐIỀN (người dùng báo tiếp): **cộng · trừ · nhân điền TỪ PHẢI SANG TRÁI**
--     (ô “nhớ” điền NGAY SAU hàng sinh ra nó), **phép chia điền TỪ TRÁI SANG PHẢI** rồi tới số dư.
--     Trước đây ô được đếm theo thứ tự vẽ nên bé điền ĐÚNG SỐ vào SAI HÀNG vẫn được báo đúng.
--     Nay thứ tự là hàm thuần `thuTuOTrong()` trong `columnMath.js` + cổng kiểm
--     `scratch/kiem-tra-thu-tu-o-dien.mjs` (18/18 ca, canary hai vế bắt được cả 4 kiểu sai).
--     ⚠️ Đây là sửa MÃ — dán lại seed KHÔNG cần thiết, chỉ cần deploy web / build APK.
--   ✅ Cổng tĩnh **32 PASS** · `soat-phep-tinh` 0 sai · `soat-o-trong` 0 · `build:web` exit 0.
--   ⚠️ Quy mô: 2 738 → **2 774 slide** (L1 697 · L2 713 · L3 763 · L4 329 · L5 272); số bài 460 không đổi.
--   ⚠️ LẦN NÀY CẦN DÁN: `02-bai-lop-1.sql`, `03-bai-lop-2.sql`, `04-bai-lop-3.sql`,
--      `05-bai-lop-4.sql` rồi `100-...`.
--
--   📐 **ĐẶT TÍNH CHIA ĐIỀN ĐƯỢC (cùng ngày, nốt dạng bài cuối):** `cotTinh` nhận thêm dấu `:`
--      với bố cục riêng của phép chia: số bị chia ở trên · vạch dọc · số chia bên phải · dưới
--      vạch ngang là các ô **thương** (bé điền **trái → phải** đúng thứ tự bé chia) · ô **số dư**
--      có nhãn “dư” khi phép chia có dư. Đáp án KHÔNG khai trong dữ liệu — hàm `tinhChia()` tính
--      thương + số dư, nên dữ liệu và đáp án không thể lệch nhau.
--      Đã thêm: Lớp 3 — `g3-c4-l4` (12 : 3) · `l5` (13 : 3, dư 1) · `l6` (48 : 4) · `l9` (19 : 3, dư 1);
--      Lớp 4 — `g4-c2-l12` (128 472 : 6) · `g4-c2-l13` (84 : 21).
--      ✅ Cổng `scratch/kiem-tra-dat-tinh.mjs` nay **44 ca** (thêm 7 ca chia + canary).
--      ✅ Cổng `scripts/test-admin-portal.mjs --static` nay **CHẶN** `cotTinh` chia số thập phân
--         (Lớp 5 chưa vẽ được kiểu đặt tính cho số thập phân) và chia cho 0.
--      ⚠️ Số slide KHÔNG đổi (2738) vì mỗi slide chỉ THAY một hình phép tính cũ bằng hình chia.
--      ⚠️ LẦN NÀY CẦN DÁN: `04-bai-lop-3.sql`, `05-bai-lop-4.sql` rồi `100-...`.
--
--   📐 **THÊM BẢNG ĐIỀN + ĐẶT TÍNH CHO LỚP 4–5 (cùng ngày):** công cụ `scratch/dem-dang-bai-sgk.mjs`
--      đếm dạng bài trong SGK ("số thích hợp", "đặt tính rồi tính", "nối"…) và số hình tương tác
--      trong app theo từng lớp ⇒ phát hiện **Lớp 4 và Lớp 5 TRƯỚC ĐÓ KHÔNG CÓ HÌNH ĐIỀN NÀO**
--      (`cotTinh`/`bangTinh` = 0) dù SGK dùng “đặt tính rồi tính” 35–40 lần.
--      Đã thêm: Lớp 4 — `g4-c2-l1` (35 480 + 24 150 · 70 000 − 15 000) · `g4-c2-l7` (1 423 × 3) ·
--      `g4-c2-l11` (245 × 12) · `g4-c6-l1` (483 526 + 254 138) · `g4-c1-l9` (bảng điền đổi yến/tạ/tấn);
--      Lớp 5 — `g5-c2-l4` (38,5 + 24,15) · `l5` (50 − 23,75) · `l6` (1,2 × 0,4) · `g5-c5-l2`
--      (12,5 × 3,2 · 15,82 + 9,35) · `g5-c2-l1` (bảng đếm chữ số phần thập phân); Lớp 2 — `g2-c1-l4`
--      (bảng điền “số liền sau”).
--      ⚠️ Số slide ĐÃ ĐỔI: 2725 → **2738** (Lớp 4: 324 · Lớp 5: 271 · Lớp 2: 704). Số bài KHÔNG đổi.
--      ⚠️ LẦN NÀY CẦN DÁN: `03-bai-lop-2.sql`, `05-bai-lop-4.sql`, `06-bai-lop-5.sql` rồi `100-...`.
--
-- LƯU Ý LẦN 17 (2026-09-26): ĐẶT TÍNH ĐIỀN ĐƯỢC Ở **LỚP 2–4** + THÊM **PHÉP NHÂN** CHO `cotTinh`.
--   Cùng họ việc với LẦN 16 (dạng “Đặt tính rồi tính” của SGK có ở gần như mọi chương 1–5):
--   chuyển nốt các slide còn **in sẵn cả cột** (trẻ đọc luôn kết quả) sang `cotTinh`, và **bộ vẽ
--   `cotTinh` nay nhận thêm dấu `×`** (hàng “nhớ” chỉ vẽ khi thừa số thứ hai có MỘT chữ số —
--   đúng dạng SGK Lớp 3–4 hay viết nhớ). Số thập phân của phép nhân theo đúng quy tắc SGK Lớp 5:
--   **số chữ số thập phân của tích = TỔNG hai thừa số** (`0,5 × 0,4 = 0,20`).
--     • Lớp 2: `g2-c1-l8` (32 + 14 · 57 − 23) · `g2-c12-l1` (235 + 412) · `l2` (256 + 173,
--       có HÀNG NHỚ) · `l3` (265 + 148) · `l4` (645 − 213) · `l5` (534 − 268) · `l6` (420 − 165) ·
--       `l9` (372 + 259 · 700 − 285) · `g2-c14-l2` (46 + 38 · 83 − 47) · `l3` (256 + 173 · 534 − 268).
--     • Lớp 3: `g3-c1-l2` (356 + 127 · 534 − 268) · `g3-c4-l1` (**32 × 3**) · `l2` (**26 × 3**, có nhớ).
--     • Lớp 4: bỏ 2 hình phép tính thừa ở slide khái niệm `g4-c6-l1` và `g4-c6-l9` (slide đã có
--       bảng số liệu + gạch đầu dòng, để thêm hình phép tính là hai hình một slide).
--   ✅ Cổng toán `scratch/kiem-tra-dat-tinh.mjs` nay **35 ca** (thêm nhân: `32 × 3` · `142 × 3` ·
--      `12 × 12` · `1,2 × 3 = 3,6` · `0,5 × 0,4 = 0,20` · canary hai vế).
--   ✅ Đo lại trong app (390×844): hình **313–330 px**, chữ đề bài 76 px, ô “?” 64 px, nút 44 px →
--      khối nút chỉ cao bằng ~nửa hình; 0 tràn ngang.
--   ⚠️ Số slide ĐÃ ĐỔI: 2715 → **2725** (Lớp 2: 695 → **703** · Lớp 3: 742 → **744**; Lớp 1, 4, 5
--      KHÔNG đổi). Số bài: 460 (không đổi).
--   ⚠️ LẦN NÀY CẦN DÁN: `03-bai-lop-2.sql`, `04-bai-lop-3.sql`, `05-bai-lop-4.sql` rồi `100-...`.
--
-- LƯU Ý LẦN 16 (2026-09-25): **“ĐẶT TÍNH RỒI TÍNH” NAY ĐIỀN ĐƯỢC** (dạng bài phổ biến nhất của SGK 1–5).
--   Trước: app chỉ in một cột CHỮ trong `text` kèm `operation` — trẻ đọc luôn kết quả, không có gì để làm.
--   Nay có khoá hình mới **`cotTinh`**: vẽ đúng cột đặt tính (thẳng hàng theo chữ số, có gạch ngang,
--   hàng “nhớ” khi cần) và **bé bấm từng ô ? rồi chọn chữ số 0–9**. Chấm NGAY: đúng → ô hiện số,
--   sai → ô đỏ, có tiến độ `1/2`, `2/2`, pháo giấy và nút “Làm lại”.
--   📌 **Đáp án KHÔNG khai trong dữ liệu** — hàm thuần `columnMath.js` tự tính từ `left`/`right`/`sign`
--      (hỗ trợ cả số thập phân `15,82 + 9,35`) ⇒ không thể có chuyện dữ liệu lệch đáp án.
--      Dữ liệu chỉ ghi: `cotTinh: { left: 25, right: 4, sign: "+" }` (`sign`: `"+"` hoặc `"−"`).
--   • Lớp 1 `g1-c8-l1`: tách thành 2 slide — bảng hàng “25 gồm 2 chục và 5 đơn vị” + **đặt tính 25 + 4**.
--   • Lớp 1 `g1-c8-l2`: **đặt tính 34 + 5**. Cả hai đã bỏ cột in sẵn trong `text` (đó chính là đáp án in sẵn).
--   ⚠️ PHẦN NÀY GỒM CẢ **MÃ** (`interactiveColumn.jsx`, `columnMath.js`, `VisualBlock.jsx`,
--      `visualKeys.js`) — dán SQL thôi CHƯA thấy; phải deploy web / build APK lại.
--   ✅ Cổng mới `node scratch/kiem-tra-dat-tinh.mjs` — **29 ca** (cộng có nhớ, trừ có mượn, số thập phân,
--      số 0, nhớ nhiều cấp, canary hai vế). Luật mới trong `scratch/kiem-tra-slide.mjs`: thiếu
--      `left`/`right`, dấu lạ, trừ ra số ÂM, hoặc đặt trên slide không cho bấm ⇒ ĐỎ.
--   ✅ Đo trong app (390×844): ô chữ số cao **31–34 px**, hình rộng 306 px, **0 tràn ngang**;
--      thử thật: bấm ô ? → chọn 4 (sai, ô xám) → chọn 9 (đúng) → 1/2 → chọn 2 → **2/2 + “🎉 Bé làm
--      đúng hết!” + pháo giấy**, nút chọn khoá lại.
--   ⚠️ Số slide ĐÃ ĐỔI: 2712 → **2713** (Lớp 1: 690 → **691**); số bài KHÔNG đổi (460).
--   ⚠️ LẦN NÀY CẦN DÁN: `02-bai-lop-1.sql` rồi `100-...` (file này). Các file lớp khác KHÔNG đổi.
--
--   📐 **SỬA CỠ + VÙNG CHẠM + BỐ CỤC (cùng ngày, người dùng gửi ảnh):** “danh sách số để chọn đang
--      quá lớn, trong khi đề bài quá nhỏ, nhìn quá xấu và không cân đối”. Công cụ đo mới
--      `scratch/do-can-doi-hinh.mjs` (chạy trong APP THẬT ở 390 px) tìm ra **3 lỗi thật**:
--        1. `FillBar` luôn vẽ nút `58×50 · chữ 24` ⇒ với bàn phím **0–9** thì nút to hơn cả đề bài.
--           Nay nút tự co theo số lựa chọn (`>= 5` lựa chọn ⇒ 44×44, vẫn đạt chuẩn vùng chạm).
--        2. **Bảng điền `bangTinh` có ô “?” chỉ bấm được 18 px** (hàng cao 28 đơn vị) — trẻ không
--           bấm nổi. Nay hàng cao 56 ⇒ ô “?” **47 px**, chữ trong bảng 19→30 px, khung hẹp lại (300)
--           để tự phóng to.
--        3. **`patternRow` có ô chỉ ~25 px.** Nay ô 44 đơn vị, tối đa 5 ô/hàng rồi **tự xuống hàng**
--           ⇒ ô ≈ 47–58 px.
--      Và **khối đặt tính được phóng to** (khung = đúng bề rộng khối số + lề) ⇒ chữ số trong đề
--      bài 76 px > nút 44 px — đúng thứ tự: ĐỀ BÀI là chính, nút là phụ.
--      Ngoài ra `FillBar` nay xếp **3 hàng riêng** (tiêu đề · nút chọn · tiến độ + “Làm lại”):
--      trước đây bốn thứ nằm chung hàng flex-wrap nên nút “10” rơi xuống hàng dưới còn “0/4” chen
--      ngay cạnh nút cuối — nhìn như lỗi.
--      ✅ Đo lại: 9 slide tương tác (bangTinh · cotTinh · numberScene) ⇒ **0 ca cần sửa**;
--      47 slide đủ 21 loại hình ⇒ chữ nhỏ nhất ≥ 13 px; 36 slide đồng hồ ⇒ ≥ 12 px; 0 tràn ngang.
--      ⚠️ Phần này là **MÃ** — không đổi dữ liệu (trừ 4 slide Lớp 1 CĐ8: `g1-c8-l3` 32+14 ·
--      `l5` 39−5 · `l6` 48−6 · `l7` 57−23 nay là `cotTinh`), nên **cần deploy web / build APK**.
--      ⚠️ Nếu dán lại seed thì vẫn chỉ cần `02-bai-lop-1.sql` rồi `100-...`; quy mô KHÔNG đổi (2713).
--
-- LƯU Ý LẦN 15 (2026-09-25): CHỦ ĐỀ 9 LỚP 1 + **HÌNH ĐỒNG HỒ KHÔNG BAO GIỜ HIỆN RA** (Lớp 2–4).
--   🔴 Phát hiện nặng: `LessonPage.jsx` chỉ vẽ `number` · `operation` · `comparison` · `clock`
--   trong slide `type: "visual"`. Slide `story` / `quiz` / `summary` chỉ gọi `VisualBlocks`, mà
--   `VisualBlocks` vẽ theo `HINH_KEYS` — trong đó KHÔNG có 4 khoá đó ⇒ dữ liệu đặt `clock` lên
--   slide câu hỏi thì ĐỒNG HỒ KHÔNG HIỆN, im lặng, không lỗi, không cảnh báo. Đo được **22 ca**
--   (Lớp 2–4). Công cụ mới: `node scratch/soat-hinh-khong-hien.mjs` (bảng bản đồ vẽ theo từng
--   kiểu slide + canary 10/10 hai vế; đã bỏ 2 ca báo oan vì `ConceptSlide` CÓ vẽ `clock`).
--   Cách chữa: thêm khối dùng chung `CalcFigures` (số · phép tính · đồng hồ · so sánh) rồi gọi
--   ở `StorySlide` · `ConceptSlide` · `QuizSlide` ⇒ **23 hình hiện ra** (9 story · 11 quiz · 3 concept).
--   ⚠️ PHẦN NÀY LÀ **MÃ** (`client/src/pages/LessonPage.jsx`) — dán SQL thôi CHƯA thấy hình mới;
--      phải deploy web / build APK lại. Dữ liệu bên dưới chỉ là phần đổi đề bài.
--   • Chủ đề 9 Lớp 1 (SGK tr.72–87): 4 câu hỏi đổi từ **mô tả kim bằng chữ** (“Kim ngắn chỉ số 7,
--     kim dài chỉ số 12…”) sang **cho HÌNH đồng hồ** + đề ngắn “Đồng hồ chỉ mấy giờ?” — đúng kiểu
--     SGK in hình cho trẻ đọc. Lời giải thích giữ nguyên trong `mascotHint` (`g1-c9-l2` ×2, `l4`, `l9`).
--   • Lớp 2 (`g2-c6`) và Lớp 3 (`g3-c13`): 6 câu hỏi bỏ phần mô tả kim khỏi đề (hình đồng hồ đã có).
--   • Lớp 3 `g3-c8-l5`, `g3-c8-l6` (chữ số La Mã): mặt đồng hồ nay vẽ **số La Mã I…XII**
--     (`clock.roman = true`) — trước đây hình vẽ số 1…12, NGHỊCH với chữ “mặt đồng hồ cổ ghi I, II, III”.
--     Đo thật ở 380 px: 12 nhãn, **0 nhãn chồng nhau**, cách tâm gần nhất 20 px.
--   • `g2-c3-l2` “Cân đồng hồ có kim chỉ số…” — đó là **cái cân**, không phải đồng hồ ⇒ bỏ `clock`,
--     thay bằng hình ⚖️ (nếu để nguyên thì vừa rồi hình cái CÂN sẽ hoá thành ĐỒNG HỒ).
--   ✅ Kiểm: `node scratch/soat-hinh-khong-hien.mjs` = 0 ca · `soat-o-trong` = 0 ô trống tĩnh ·
--      `soat-phep-tinh` = 0 sai · cổng tĩnh **32 PASS** · `build:web` exit 0.
--   ⚠️ Số bài và số slide KHÔNG đổi: 5 lớp · 51 chương · **460 bài · 2814 slide**.
--   ⚠️ LẦN NÀY CẦN DÁN: `02-bai-lop-1.sql`, `03-bai-lop-2.sql`, `04-bai-lop-3.sql` rồi `100-...`.
--      `01`, `05`, `06`, `99` KHÔNG đổi. `00` không cần (không bài nào bị bỏ).
--
-- LƯU Ý LẦN 14 (2026-09-25): CHỦ ĐỀ 7 LỚP 1 — THÊM **BÀI CÒN THIẾU** “CAO HƠN, THẤP HƠN” (SGK tr.30–31).
--   SGK có hẳn một phần “Cao hơn, thấp hơn” (Bài 25) mà app KHÔNG có bài nào (nhóm lỗi A).
--   Bài mới: `g1-c7-l9` — chèn ở VỊ TRÍ THỨ 2 (giữ id mới để không mất tiến độ của bé), sau đó
--   đánh số lại bằng `node scratch/chuan-hoa-danh-so.mjs client/src/data/grade1/g1c7.js` ⇒ nay là
--   “Bài 2: Cao hơn, thấp hơn”: kể chuyện · khám phá · **biểu đồ cột** so chiều cao ba cây ·
--   3 câu hỏi (cao hơn · thấp hơn · hươu cao cổ vs ngựa) · ghi nhớ ⇒ **7 slide**.
--   ⏸ CHƯA làm (cần người dùng CHỐT, không đoán số): “Chọn số đo độ dài phù hợp” tr.36 và bài
--   đếm đồ chơi trên lưới ô vuông tr.38 — sách in sẵn/tô sẵn, ảnh không đủ để chốt đáp án.
--   ⚠️ Số slide ĐÃ ĐỔI: 2705 → **2712** · số bài: 459 → **460** (Lớp 1: 690 slide · 98 bài).
--   ⚠️ LẦN NÀY CẦN DÁN: `02-bai-lop-1.sql` rồi `100-...` (file này).
--
--   Đã xem ảnh sách tr.5, 6, 14, 15, 23; phần chữ các trang khác lấy từ OCR (tách theo trang).
--     • `g1-c6-l4`: bảng **“gồm mấy chục, mấy đơn vị”** → `bangTinh` (LT2 tr.14) · bảng số 0–99
--       còn thiếu 12 ô → dãy số điền được (LT1 tr.14).
--     • `g1-c6-l5`: 2 câu hỏi từ trò chơi “Cánh cụt câu cá” (tr.15).
--     • `g1-c6-l7`: 2 câu hỏi bài toán lớp 1A/1B/1C (tr.21).
--     • `g1-c6-l10`: 3 dãy “Số ?” tr.23 (đếm thêm 1 · đếm thêm 2 · dãy lớn).
--     • `g1-c6-l11`: 2 hàng bảng số 51–60 và 71–80 (tr.22) · câu hỏi “số ngay dưới 23” (tr.23).
--     • `g1-c6-l12`: 2 câu hỏi luyện tập chung (tr.25).
--   ⚠️ Số slide ĐÃ ĐỔI: 2692 → **2705** (Lớp 1: 670 → **683 slide**).
--   ⚠️ LẦN NÀY CẦN DÁN: `02-bai-lop-1.sql` rồi `100-...` (file này).
--
--   + 2 slide “Số ?” mới của Chủ đề 6 theo SGK tr.5–6.
--   Phát hiện nhờ **sửa thước đo**: công cụ soát trước đó xếp nhầm 13 `mode` của `numberScene` vào nhóm
--   “tự tương tác”, trong khi đọc mã thì chỉ có 3 nhánh thật sự tương tác (`numberMaze`, `dotCards`,
--   `comparePairs`) ⇒ 2 slide này bị bỏ qua dù trẻ không bấm được gì.
--     • `g1-c1-l4` slide 9 — dãy số 0 → 10, 4 ô trống (`answers: [2, 3, 7, 10]`).
--     • `g1-c1-l11` slide 7 — 6 đoàn tàu (SGK tr.40), 6 ô `?` (`answers: [5, 4, 5, 8, 9, 1]`).
--   Bộ vẽ: `TrainFill` (`Grade1NumberVisuals.jsx`) — bản tĩnh và bản điền được dùng CHUNG một hàm vẽ;
--   dãy dài tự chia nhiều hàng (SGK tr.5 có dãy 1 → 20).
--   Thêm cho Chủ đề 6 (`g1-c6-l2`): dãy **1 → 20** có 4 ô “?” (SGK tr.5 HĐ3) và **6 đoàn tàu “Số ?”**
--   (SGK tr.6 LT1) — đúng 6 hàng như sách, 12 ô trống.
--   Cổng mới trong `scratch/kiem-tra-slide.mjs`: `numberTrain` có ô trống ⇒ phải có `answers` khớp số ô.
--   ⚠️ Số slide ĐÃ ĐỔI: 2690 → **2692** (Lớp 1: 668 → **670 slide**).
--   ⚠️ LẦN NÀY CẦN DÁN: `02-bai-lop-1.sql` rồi `100-...` (file này). Không cần dán các file lớp khác.
--
-- LƯU Ý LẦN 11 (2026-09-25): **MỌI Ô TRỐNG PHẢI ĐIỀN ĐƯỢC** (yêu cầu người dùng) + 6 slide CĐ6 Lớp 1.
--   Yêu cầu: “tất cả các dạng bài có điền vào ô trống không được là slide tĩnh và đều có thể điền
--   đáp án vào được; đảm bảo tất cả các dạng bài tập đều có đáp án để trẻ lựa chọn và tương tác”.
--   Công cụ soát mới: `node scratch/soat-o-trong.mjs` (2814 slide / 1439 slide cho bấm của cả 5 lớp).
--   Sửa 10 ca thật:
--     • 5 bảng CĐ3 (`g1-c3-l3/l4/l8/l9/l14`) từ bảng IN CỨNG ô “?” → **`bangTinh`** (bé bấm ô, chọn số).
--     • 2 bảng Lớp 3 (`g3-c1-l4` tìm số bị trừ · `g3-c2-l9` nhân–chia) → `bangTinh`, hàng đầu giữ làm MẪU.
--     • 1 bảng Lớp 2 (`g2-c13-l1` phân loại) → ví dụ có số thật (7 bạn · 4 bạn), bỏ hẳn ô “?” vì bảng
--       đó không có số liệu nào để bé điền.
--     • 3 dãy hình (`g1-c2-l8` ×2 · `g1-c5-l4`) → `patternRow` **nay bé chọn HÌNH để điền**.
--   Bộ vẽ mới `bangTinh` (`interactiveTable.jsx`); `FillBar` thêm `renderOption`/`tenOption`.
--   Luật mới trong `scratch/kiem-tra-slide.mjs`: bảng `table` không được in cứng ô `"?"`; `bangTinh`
--   phải khớp số đáp án/số ô + có `options`, và chỉ đặt trên slide `story/concept/visual`.
--   Kèm: **CĐ6 Lớp 1 — 6 slide** (bảng Viết số/Đọc số 11–20 theo SGK tr.4–5 + 5 câu hỏi).
--   ⚠️ Số slide ĐÃ ĐỔI: 2684 → **2690** (Lớp 1: 662 → **668 slide**).
--   ⚠️ LẦN NÀY CẦN DÁN: `02-bai-lop-1.sql` + `03-bai-lop-2.sql` + `04-bai-lop-3.sql` rồi `100-...`.
--
-- LƯU Ý LẦN 10 (2026-09-25): RÀ SOÁT **CHỦ ĐỀ 3 LỚP 1** (SGK tr.56–91) + BỔ SUNG DẠNG BÀI THEO SGK.
--   Đọc 21 trang ảnh 300 DPI (PDF 57–77 + 81 + 87) đối chiếu 14 bài `g1-c3-l1` … `l14`.
--   Kiểm từng câu: app **KHÔNG sai phép tính nào** (3+2, 4+3, 2+5=5+2, 5+0, 9−3, 4−4, 10−5, 3+?=7 …).
--   Bổ sung **12 slide** cho các dạng bài SGK mà app còn thiếu:
--     • **Bảng tính — điền số ?** (SGK lặp 6 lần trong chương này) ở 5 bài:
--       `l3` (tr.64, các phép cộng đều bằng 9) · `l4` (tr.62, đều bằng 7) ·
--       `l8` (tr.66, đều bằng 10) · `l9` (tr.76, 7 trừ dần) · `l14` (tr.86, quan hệ cộng–trừ trong 10).
--     • **Cộng ba số** `3 + 1 + 2 = 6` (`l4`, SGK tr.66) — trước đây CẢ 5 LỚP không có dạng này.
--   ⚠️ Số slide ĐÃ ĐỔI: 2659 → **2671** (Lớp 1: 637 → **649 slide**).
--   ⚠️ LẦN NÀY CẦN DÁN: `02-bai-lop-1.sql` rồi `100-...` (file này).
--
-- LƯU Ý LẦN 9 (2026-09-25): RÀ SOÁT **CHỦ ĐỀ 2 LỚP 1** THEO SGK (tr.46–55).
--   Mở 10 ảnh trang sách 300 DPI (PDF 47–56) đối chiếu 8 bài `g1-c2-l1` … `l8`.
--   Sửa 6 lỗi nội dung thật:
--     • `l1`: bỏ “mặt đồng hồ vuông có dạng hình vuông” — SGK dùng ĐỒNG HỒ làm ví dụ
--       HÌNH TRÒN (tr.46), và chính bài `l2` dạy “mặt đồng hồ tròn xoe”.
--     • `l1`: bỏ vế “4 góc vuông” (góc vuông là nội dung LỚP 3).
--     • `l2`: “Hình tròn lăn được” → “Bánh xe có dạng hình tròn nên lăn được”.
--     • `l7`: thống nhất ngôi nhà **2 cửa sổ vuông** (trước: kể chuyện 1, ghi nhớ 2).
--     • `l5`: 4 slide “xem hình” → 4 CÂU HỎI đúng SGK tr.46 HĐ1 (đồng hồ/gạch/mái/sách),
--       hình không in sẵn đáp án (`showShape: false`).
--     • `l8`: thêm 3 câu hỏi kiểu SGK tr.47/49 (chọn nhiều hình A–E; “KHÔNG là hình vuông”).
--   ⚠️ Số slide ĐÃ ĐỔI: 2656 → **2659** (8 bài CĐ2: 48 → 51 slide) ⇒
--      vẫn 5 lớp · 51 chương · 460 bài · **2814 slide**.
--   ⚠️ LẦN NÀY CẦN DÁN: `02-bai-lop-1.sql` · `03-bai-lop-2.sql` · `04-bai-lop-3.sql`
--      rồi `100-...` (file này). `00`, `01`, `05`, `06`, `99` KHÔNG đổi.
--
-- LƯU Ý LẦN 8 (2026-09-25): BỎ PHƯƠNG ÁN VÔ NGHĨA Ở CÂU "ĐIỀN DẤU" + XẾP 3 PHƯƠNG ÁN MỘT HÀNG.
--   Người dùng gửi ảnh chụp slide "Điền dấu thích hợp: 6 ? 6" có 4 phương án `> < = −`
--   và hỏi: "dấu này là dấu gì? tại sao phép so sánh lại có dấu trừ ở đây?".
--   Đúng vậy: câu so sánh chỉ có 3 đáp án, còn `+` / `−` là phương án nhiễu VÔ NGHĨA
--   (di chứng của quy tắc cũ "câu nào cũng phải đủ 4 phương án").
--   Đã xoá ở **7 chỗ**: `g1c1.js` x5 (3 ? 5 · 6 ? 6 · 4 ? 7 · 8 ? 7 · 4 ? 4),
--   `g1c5.js` (4 ? 9), `g1c10.js` (63 ? 36).
--   Kèm theo: quiz có ĐÚNG 3 phương án NGẮN (≤ 2 ký tự) nay xếp MỘT HÀNG 3 ô
--   (`LessonPage` thêm lớp `quiz-options-3`; số đáp án LẺ mà đáp án DÀI thì ô cuối canh giữa).
--   Phần DỮ LIỆU cần dán; phần XẾP Ô là MÃ (`client/…`) nên phải deploy web / build APK mới thấy.
--   Công cụ soát: `node scratch/soat-phuong-an-quiz.mjs` — 786 câu · 0 lỗi.
--   ⚠️ LẦN NÀY CHỈ CẦN DÁN: `02-bai-lop-1.sql` rồi `100-...` (file này). `00` không cần;
--      `01`, `03`, `04`, `05`, `06`, `99` KHÔNG đổi.
--   ⚠️ Số slide KHÔNG đổi (lần này chỉ sửa phương án + cách xếp ô).
--   ✅ Kiểm trên app: Lớp 1 Bài 8 (`g1-c1-l8`), slide 10/14 phải CHỈ có 3 nút `> < =`
--      (không còn `−`) và 3 nút nằm CÙNG MỘT HÀNG.
--
-- BỐI CẢNH LẦN NÀY (2026-09-24, lần 6): VIẾT LẠI CHỦ ĐỀ 4 LỚP 1 THEO SGK (tr.92–101).
-- BỐI CẢNH LẦN NÀY (2026-09-24, lần 7): VIẾT LẠI **CHỦ ĐỀ 1 LỚP 1** THEO SGK (tr.6–45).
--   Yêu cầu người dùng: “bổ sung thêm trong plan là rà soát file scan của TẤT CẢ các trang tài liệu
--   học của Lớp 1… sau khi xong Lớp 1 thì tới Lớp 2,3,4,5: tất cả các lớp đều phải rà soát hết
--   tất cả file ảnh để đồng bộ và nâng cao chất lượng”.
--   Bảng phát hiện chi tiết được giữ riêng trên máy (không đẩy lên GitHub).
--   12 bài của Chủ đề 1 (`g1-c1-l1` … `g1-c1-l12`) viết lại theo ĐÚNG 7 bài của SGK:
--   **67 slide cũ → 128 slide**, **47 lượt hình**.
--   Đổi cho khớp sách: số 0 nay học CÙNG nhóm 0–3 (SGK tr.8) thay vì đứng riêng sau 6–10;
--   bỏ dạy trước “5 > 4” ở bài số 4–5 (dấu so sánh để đúng bài 8); bài cuối là
--   Luyện tập chung **tiếp theo** của SGK tr.42–45. Có dạy **chữ đọc số** (một, hai, ba…).
--   KHÔNG làm theo yêu cầu người dùng: “Tập viết số” (tr.9, 15) và 2 trò chơi bàn cờ có
--   xúc xắc (tr.19, tr.43).
--   Số liệu tự chọn (ảnh scan mờ, đã ghi vào bảng §7 của kế hoạch): cà rốt tô màu 3 củ ·
--   gà ghi số 2 là 3 con · 4 con vật 6 chân · số vật trong 4 tranh cảnh · các cặp “cho thêm”.
--   ⚠️ LẦN NÀY CHỈ CẦN DÁN: `02-bai-lop-1.sql` rồi `100-...` (file này).
--   ⇒ Quy mô của lần 7: 5 lớp · 51 chương · **459 bài · 2656 slide** (nay là 2671 — xem LẦN 10).
--
-- 📌 LẦN 6 (2026-09-24): VIẾT LẠI CHỦ ĐỀ 4 LỚP 1 THEO SGK (tr.92–101).
--   Người dùng yêu cầu: “giúp trẻ dễ học bài hơn, luôn luôn có hình minh họa chính xác,
--   tận dụng các hoạt động rất hay trong SGK thay vì những slide đơn điệu”.
--   7 bài của Chủ đề 4 (`g1-c4-l1` … `g1-c4-l7`) được viết lại: 39 slide cũ → **68 slide**,
--   mỗi bài đều theo cấu trúc SGK: Kể chuyện → Khám Phá → Hoạt động/Thực hành → Luyện tập
--   → Ghi nhớ; và mỗi bài đều có hình (không còn slide chữ suông).
--   Đáp án LẤY TỪ CHÍNH SGK (đo lại trên ảnh 300 DPI, không đoán):
--     • Lâu đài bạn Mai (tr.94): hàng nền **5 khối lập phương**, **2** khối hộp chữ nhật đỏ.
--     • Chữ T/H/C (tr.94): T = 5 · H = 7 · C = 5 ⇒ chữ H nhiều khối nhất.
--     • Bộ hình A–G (tr.100): **A, C, E** là khối lập phương (mặt trước ĐO ĐƯỢC là vuông:
--       105×105 · vuông nhỏ · 168×159) — **B, G** là khối hộp chữ nhật; D là khối trụ.
--     • Con xúc xắc (tr.100): mặt trước **5** chấm · mặt bên phải **6** chấm · mặt trên **3** chấm
--       (cũng đúng quy luật xúc xắc thật: 5+2 = 3+4 = 6+1 = 7 ⇒ số đo tự kiểm chéo).
--     • Hai hình xếp bằng khối nhỏ (tr.101): trái 8 khối · phải 4×2 = 8 khối ⇒ “bằng nhau”.
--     • Ba hàng gạch (tr.97): 2 + 3 + 4 = 9 viên; hai hàng bạn xem ti vi: 6 + 4 = 10 bạn
--       (người dùng đếm lại trên sách giấy ngày 2026-09-24).
--   ⚠️ LẦN NÀY CHỈ CẦN DÁN: `02-bai-lop-1.sql` rồi `100-...` (file này).
--      `01`, `03`, `04`, `05`, `06`, `99` KHÔNG đổi. `00` không cần (không bài nào bị bỏ).
--   ⇒ Quy mô LẦN ĐÓ: 5 lớp · 51 chương · **459 bài · 2484 slide** (nay là 2545 — xem lần 7).
--
-- 📌 LẦN 5 (2026-09-22): GHI TÊN ĐIỂM LÊN HÌNH (A, B, C, D, M, O…).
--   Người dùng báo: "mô tả hình chữ nhật có cạnh AB và BC và 4 đỉnh A, B, C, D nhưng lại
--   không ghi chú A, B, C, D lên trên hình thì làm sao trẻ hiểu được?". Soát ra cả một họ
--   lỗi: chữ trong bài GỌI TÊN ĐIỂM mà trên hình không có chữ nào.
--     • Hình tứ giác ABCD (Lớp 2): nay mỗi đỉnh có ĐÚNG TÊN của nó (A, B, C, D) và mỗi cạnh
--       ghi tên cạnh (AB, BC, CD, DA) — trước đây chỉ có một chữ "đỉnh" chung.
--     • BỘ VẼ MỚI "điểm và đường": các bài "đoạn thẳng AB", "đường gấp khúc ABCD", "ba điểm
--       thẳng hàng" trước đây vẽ bằng… CÁI THƯỚC ĐO, hoặc không có hình nào (chữ A, B, C, D
--       chỉ nằm trong đoạn văn, viết dạng "A •———• B"). Nay vẽ đúng: ĐIỂM (chấm tròn) + TÊN
--       ĐIỂM, gồm đoạn thẳng, đường thẳng, đường cong, đường gấp khúc, ba điểm thẳng hàng,
--       ba điểm KHÔNG thẳng hàng, và trường hợp chỉ có hai điểm rời — dùng cho câu hỏi "nối
--       hai điểm A và B được hình gì?" (cố ý KHÔNG vẽ sẵn đoạn thẳng, vẽ là cho luôn đáp án).
--     • Lớp 3: "góc đỉnh A, cạnh AB và AC" nay có chữ A ở đỉnh, B và C ở hai đầu cạnh;
--       "trung điểm M của AB" nay vẽ đúng đoạn A·M·B có vạch bằng nhau ở hai nửa (thấy
--       AM = MB), "O là điểm ở giữa A và B" vẽ đúng ba điểm A, O, B — thay cho cái thước.
--     • Lớp 3 hình tròn: nay ghi tên từng điểm — tâm O, hai đầu đường kính là B và C, điểm A
--       trên đường tròn — để khớp câu "bán kính OA = OB, đường kính BC".
--     • Lớp 4: "góc nhọn đỉnh O, hai cạnh OA và OB" nay có chữ O, A, B ngay trên hình.
--     • Lớp 5: hình tròn ghi đúng chữ mà công thức dùng — bán kính r, đường kính d.
--   Công cụ soát thêm 2 họ lỗi: F = chữ gọi tên điểm mà hình không ghi tên (11 chỗ → 3 chỗ;
--   3 chỗ còn lại là 1 câu hỏi mà vẽ hình là cho luôn đáp án + 2 bài toán lời văn, KHÔNG sửa);
--   G = bài đoạn thẳng có tên mà hình lại là thước đo (nay 0 chỗ).
--   Số bài và số chương KHÔNG đổi; số slide TĂNG vì mỗi hình được tách ra một slide.
--   ⇒ Quy mô LẦN ĐÓ: 5 lớp · 51 chương · **459 bài · 2455 slide** (nay là 2484 — xem lần 6).
--   ⚠️ LẦN NÀY BẮT BUỘC dán `02`, `03`, `04`, `05` VÀ `06` (cả NĂM lớp đều có thay đổi).
--      `01` và `99` không đổi. `00-don-noi-dung-cu.sql` KHÔNG cần (không bài nào bị bỏ),
--      nhưng chạy nó vẫn VÔ HẠI — nó chỉ xoá bài không còn trong file tĩnh.
--   ℹ️ NẾU DB ĐÃ DÁN LẦN ĐẦU RỒI thì lần sửa này CHỈ CẦN dán lại 2 file: `03-bai-lop-2.sql`
--      và `06-bai-lop-5.sql` (đúng 2 file chứa 6 bài vừa đổi: tứ giác thường + chữ a, b, c
--      trên cạnh khối), rồi dán `100-...` để tăng phiên bản. Không cần dán lại cả 5 file.
--      Cách kiểm chắc chắn: `node scripts/migrate-content.mjs --verify` ⇒ phải ra
--      **"Bài có nội dung khác: 0"**. Còn số khác 0 thì seed đang CŨ hơn dữ liệu (hoặc dán
--      thiếu file) — chạy `node scripts/migrate-content.mjs --sql` để sinh lại rồi dán lại.
--      Cổng `S-32` (`npm run test:portal:static`) canh đúng chuyện này, không thể quên nữa.
--
-- 📌 LẦN TRƯỚC (lần 4): 7 lỗi hình học ở Lớp 1 CĐ 2 — hình vuông bị vẽ thành hình chữ nhật
--   (17 chỗ ở cả 5 lớp), nói "3 cạnh · 3 đỉnh" mà hình không có đỉnh nào, đồ vật vẽ quá nhỏ,
--   ghép hình mà không thấy cách ghép, slide nhồi nhiều hình, nhà vẽ sai, câu hỏi thiếu hình.
--   Nay có bộ vẽ ĐỒ VẬT THẬT (10 kiểu) và bộ vẽ GHÉP HÌNH.
-- 📌 LẦN TRƯỚC (lần 3): sửa lỗi hiển thị hình + thêm hình cho câu hỏi — khung 10 ô khai thiếu
--   số liệu (bài 9 + 4 khai `extra: 3` trong khi phải là 4), 16 câu hỏi nay có hình (đếm chim,
--   "trên biểu đồ", thước đo, sơ đồ hai băng giấy), bỏ 2 câu trỏ vào hình không tồn tại.
--
-- 📌 LẦN TRƯỚC (lần 2): bổ sung HÌNH MINH HOẠ — thêm 17 kiểu hình vẽ SVG (trục số, khung
--   10 ô, bảng hàng, thước đo, tiền Việt Nam, hình phẳng/khối, phân số, sơ đồ đoạn thẳng,
--   sơ đồ chuyển động, biểu đồ cột/quạt…) vào cả 459 bài. DB nào chưa từng nạp lần 2 thì các
--   file seed dưới đây vẫn bao trùm đủ cả hai lần — cứ dán theo đúng thứ tự là xong.
-- 📌 LẦN TRƯỚC NỮA: dựng lại chương trình Lớp 1–3 theo đúng số chủ đề SGK (Lớp 1: 10 ·
--   Lớp 2: 10 → 14 · Lớp 3: 10 → 16). Khi đó số bài ĐỔI và có **79 bài mồ côi** buộc phải
--   dọn bằng `00-don-noi-dung-cu.sql` chạy TRƯỚC seed (seed chỉ upsert).
-- ════════════════════════════════════════════════════════════════════════════

-- ── 1. Kiểm TRƯỚC khi đẩy: số bài từng lớp ───────────────────────────────
SELECT split_part(id, '-', 1) AS lop, COUNT(*) AS so_bai
FROM public.content_lessons
GROUP BY 1
ORDER BY 1;
-- Mong đợi: g1 = 98 · g2 = 120 · g3 = 123 · g4 = 73 · g5 = 75 (tổng 489).
--   (Lớp 1 là 98 bài chứ KHÔNG phải 97 — con số 97 trong tài liệu cũ đã lỗi thời từ lần 14.)
--   (Lớp 4 – Lớp 5 nay theo sách Kết nối tri thức: 73 bài và 75 bài — xem LƯU Ý LẦN 22.)

-- Tổng toàn hệ thống và số bài nháp (phải là 0 — seed luôn ghi `published`).
SELECT
  (SELECT COUNT(*) FROM public.content_lessons) AS tong_bai,
  (SELECT COUNT(*) FROM public.content_lessons WHERE status = 'draft') AS so_nhap,
  (SELECT COUNT(*) FROM public.content_lesson_versions) AS so_phien_ban;
-- Mong đợi: tong_bai = 489 · so_nhap = 0 · so_phien_ban >= 489 (mỗi bài ít nhất một
--   dòng v1; một số bài có thể có thêm v2, v3 … nếu admin từng publish).

-- ── 2. Đẩy phiên bản ───────────────────────────────────────────────────────
-- 🔴 ĐỪNG gọi `public.bump_content_version()` Ở ĐÂY. Đã mắc thật, nguyên văn:
--      Failed to run sql query: ERROR: 42501: Chỉ admin được đổi phiên bản nội dung
--      CONTEXT: PL/pgSQL function bump_content_version() line 6 at RAISE
--    Vì `0012` đã bọc hàm đó bằng `IF NOT public.is_admin() THEN RAISE` (để khách
--    không gọi được qua RPC — lỗ hổng `D-16` cũ), mà `is_admin()` là
--    `profiles.role = 'admin' AND id = auth.uid()`; SQL Editor KHÔNG có JWT nên
--    `auth.uid()` NULL ⇒ `is_admin()` false ⇒ hàm TỪ CHỐI. **Đúng thiết kế.**
--    ⇒ Trong SQL Editor phải làm việc TƯƠNG ĐƯƠNG bằng SQL thô dưới đây. Câu lệnh
--      này CHÍNH LÀ thân của hàm kia, chạy bằng quyền chủ sở hữu bảng nên không đi
--      qua chốt admin — kết quả y hệt, chỉ khác là không cần phiên đăng nhập.
UPDATE public.app_config
SET value = to_jsonb(
      COALESCE(
        CASE WHEN jsonb_typeof(value) = 'number' THEN (value #>> '{}')::INT END,
        CASE WHEN jsonb_typeof(value) = 'object' THEN (value ->> 'value')::INT END,
        0
      ) + 1
    ),
    updated_at = NOW()
WHERE key = 'content_version'
RETURNING (value #>> '{}')::INT AS phien_ban_moi;
-- Mong đợi: SỐ CŨ + 1. Con số CỤ THỂ không quan trọng — app chỉ cần thấy số **khác**
--   số cũ là sẽ tải lại nội dung. (Cố ý KHÔNG ghi số đo cụ thể ở đây: con số đó lệch
--   ngay sau lần chạy sau, và một "mong đợi" lỗi thời còn tệ hơn không có.)

-- ── 3. Kiểm SAU khi đẩy: công tắc vẫn phải là "remote" ─────────────────────
SELECT key, value FROM public.app_config
WHERE key IN ('content_source', 'content_version') ORDER BY key;
-- Mong đợi: content_source = "remote" · content_version = số cũ + 1.

-- ── 4. Kiểm trên app của bé (không cần SQL) ────────────────────────────────
-- Mở lại app (đúng tài khoản bé đã dùng trước đó) và xem log:
--   [nội dung] đọc từ DB: 5 lớp · 65 chương · 489 bài · 3149 slide · phiên bản N
--
-- ── 5. CÁCH KIỂM BẰNG MÁY (chạy trong repo, KHÔNG phải trong SQL Editor) ─────
--   🔴 Chạy ĐÚNG tên script, nếu không Node báo "Cannot find module":
--        npm run content:verify        ← dùng cái này (ngắn, không thể gõ sai)
--        node scripts/migrate-content.mjs --verify
--        ❌ SAI: node migrate-content.mjs --verify  (file nằm trong thư mục `scripts/`)
--   Mong đợi: "✅ KHỚP HOÀN TOÀN — 489 bài, 3149 slide." và mã thoát 0.
--
-- Kiểm ĐÚNG những chỗ từng sai — đây là lỗi mà chủ app tự phát hiện:
--   • Lớp 2 → chương về phép nhân CHỈ được có bảng nhân 2 và bảng nhân 5.
--     KHÔNG còn bảng nhân 3, 4 (trước đây nằm sai ở Lớp 2).
--   • Lớp 3 → chương 1 và chương 2 PHẢI có bảng nhân/chia 3, 4 — đây mới là chỗ đúng SGK.
--   • Lớp 2 KHÔNG còn dạy "một phần mấy" (1/2, 1/3, 1/4, 1/5) — chủ đề đó thuộc Lớp 3.
--   • Lớp 1 và Lớp 3 không còn dạy "cộng trừ qua 10" / "phân số" nữa.
--
-- Kiểm HÌNH và CÂU HỎI — đúng những chỗ vừa sửa (2026-09-22 lần 3):
--   • Lớp 2 Bài 1 (g2-c2-l1) slide 3/5: khung 10 ô phải vẽ 9 ô xanh + 1 ô xanh lá TRONG
--     khung, rồi dấu "+" và 3 ô xanh lá NGOÀI khung ⇒ tổng 13 ô.
--     🔴 Nếu chỉ thấy 10 ô, hoặc thấy "+ 2" ⇒ DÁN THIẾU: chạy lại `03-bai-lop-2.sql`.
--   • Lớp 2 (g2-c2-l2) slide 3/5: 8 ô xanh + 2 ô xanh lá trong khung, "+" và 3 ô ngoài = 13.
--   • Lớp 1 Bài 2 (g1-c1-l2) slide câu hỏi "Hình dưới đây có mấy con chim?":
--     phải thấy 3 con chim để bé đếm. Dán thiếu thì câu hỏi không có gì để nhìn.
--   • Câu hỏi có chữ "trên biểu đồ" (Lớp 2: g2-c13-l3, g2-c13-l4, g2-c13-l6, g2-c14-l7;
--     Lớp 3: g3-c15-l2, g3-c15-l4, g3-c16-l5) phải có khay hình bên dưới câu hỏi.
--   • Câu hỏi lời văn có hình: Lớp 1 (g1-c7-l4, g1-c7-l8) và Lớp 2 (g2-c5-l7) có THƯỚC ĐO;
--     Lớp 2 (g2-c1-l7, g2-c1-l9) và Lớp 3 (g3-c4-l3) có SƠ ĐỒ ĐOẠN THẲNG.
--     Số của mỗi hàng ("20 cm", "17 cm") phải nằm BÊN TRÁI, ngay trước thanh.
--   • Trục số: số ở mốc cuối KHÔNG bị mũi tên đè lên; vòng cung "nhảy" (nếu có) nông,
--     không vượt ra ngoài khung.
--   • Sơ đồ đoạn thẳng (toán Tổng–Tỉ, Lớp 4 `g4-c5-l2`): nhãn "Tổng 35" phải HIỆN ĐỦ,
--     không bị cắt ở mép phải.
--   • Đầu mỗi thẻ slide: nút đọc CHỈ CÒN ICON LOA, nhãn loại slide ("Bài học", "Quan sát",
--     "Thử thách", "Tổng kết") nằm cùng hàng; ở slide câu hỏi thứ tự là [loa] rồi [cờ].
--   • Chữ dài trong slide "hình ảnh" phải xuống dòng đúng như dữ liệu
--     (ví dụ g2-c2-l1: dòng thứ hai là "↑ tách 4 thành 1 và 3").
--
-- Kiểm HÌNH HỌC — đúng những chỗ vừa sửa (2026-09-22 lần 4). Mở app ở cỡ màn hình điện thoại
-- thật (360–375 px) rồi xem Lớp 1 Chủ đề 2:
--   • Bài 1 (g1-c2-l1), slide "Hình vuông": hình phải VUÔNG THẬT (bốn cạnh dài bằng nhau về
--     hình vẽ — không được là hình chữ nhật dài), và phải có BỐN CHẤM TRÒN ở bốn góc kèm chữ
--     "đỉnh" — vì lời giảng nói "4 cạnh dài bằng nhau · 4 đỉnh".
--   • Bài 2 (g1-c2-l2): slide kể chuyện phải có MẶT ĐỒNG HỒ vẽ hẳn ra (vòng tròn màu, 12 vạch,
--     hai kim). Nếu chỉ thấy hình tròn trơn hoặc hình quá nhỏ ⇒ dán thiếu `02-bai-lop-1.sql`.
--   • Bài 3 (g1-c2-l3): hình tam giác phải có BA CHẤM TRÒN ở ba đỉnh (lời giảng nói "3 cạnh · 3
--     đỉnh"), không chỉ có chữ "cạnh".
--   • Bài 4 (g1-c2-l4): phải thấy QUYỂN SÁCH to rõ ràng (bìa + gáy + mấy trang giấy) — không
--     còn là một hình chữ nhật trơn nhỏ xíu.
--   • Bài 5 (g1-c2-l5): KHÔNG còn một slide chứa 4 dòng chữ + bảng + hình. Nay là một dãy slide,
--     mỗi slide MỘT đồ vật to: mặt đồng hồ → viên gạch lát nền → mái nhà → quyển sách → bảng
--     tổng hợp. Cuối bài, câu hỏi "Bánh xe đạp" có BÁNH XE, câu hỏi "Cửa ra vào" có CỬA RA VÀO.
--   • Bài 6 (g1-c2-l6): slide dạy ghép hình phải thấy HAI MẢNH TAM GIÁC RỜI NHAU → mũi tên →
--     HÌNH VUÔNG kết quả có vạch đứt hai đường chéo (cho thấy hai mảnh khít vào nhau thế nào).
--     Slide câu hỏi "ghép lại được hình gì?" thì CỐ Ý chỉ có hai mảnh rời, KHÔNG có hình kết quả.
--   • Bài 7 (g1-c2-l7): phải thấy NGÔI NHÀ (mái tam giác + thân chữ nhật + cửa sổ vuông). Câu
--     hỏi thử thách phải có NGÔI NHÀ HAI CỬA SỔ để bé đếm được.
--   • Cả 5 lớp, ở 360 px và 375 px: KHÔNG phải kéo ngang mới xem hết hình; chữ trong hình
--     không đè lên nhau; không có hình nào thò ra ngoài khung thẻ.
--   • Lớp 2 Bài 6 (g2-c5-l6) slide đầu: có hình BỐN CẠNH (kèm chấm ở bốn đỉnh) để bé thấy "hình
--     có bốn cạnh" là thế nào trước khi nghe tên gọi "tứ giác".
--   • Lớp 4 Bài 6 (g4-c2-l6) và Bài 7 (g4-c4-l7), Lớp 5 Bài 5 (g5-c3-l5), Bài 6 (g5-c3-l6),
--     Bài 12 (g5-c3-l9): slide kể chuyện nay đều CÓ HÌNH (góc vuông / hình thoi / biểu đồ hình
--     quạt / hình hộp chữ nhật / hình trụ) — trước đây chỉ có chữ.
--
-- Kiểm TÊN ĐIỂM TRÊN HÌNH — đúng những chỗ vừa sửa (2026-09-22 lần 5):
--   • Lớp 2 Bài 6 tứ giác (g2-c5-l6) slide hình: hình chữ nhật phải có ĐỦ BỐN CHỮ A, B, C, D
--     ở bốn góc (mỗi góc một chữ, không phải một chữ "đỉnh" chung) và TÊN CẠNH AB, BC, CD, DA
--     viết trên bốn cạnh. Đây chính là chỗ chủ app báo "không ghi chú A, B, C, D lên trên
--     hình thì làm sao trẻ hiểu được?".
--   • Lớp 2 Chủ đề 5 (g2-c5-l1 → l4): thoát ra vào từng bài, mỗi bài phải thấy ĐIỂM CHẤM TRÒN
--     kèm CHỮ A, B (hoặc A, B, C, D với đường gấp khúc) trên một hình vẽ thật:
--     đoạn thẳng AB · đường thẳng AB kéo dài hai phía · đường cong uốn lượn · đường gấp khúc
--     ABCD (ba đoạn AB, BC, CD) · ba điểm A, B, C thẳng hàng · ba điểm A, B, C KHÔNG thẳng hàng.
--     🔴 Nếu vẫn thấy hình CÁI THƯỚC ĐO ở các slide này ⇒ DÁN THIẾU `03-bai-lop-2.sql`.
--   • Lớp 2 câu hỏi "Nối hai điểm A và B ta được hình gì?": cố ý CHỈ có hai điểm RỜI, không
--     có đoạn thẳng — vì vẽ sẵn đoạn thẳng là cho luôn đáp án. Đây là CỐ Ý, không phải lỗi.
--   • Lớp 3 (g3-c3-l1, l2, l3, l4): "O là điểm ở giữa A và B" phải thấy A · O · B trên một
--     đoạn thẳng; "M là trung điểm của AB" phải thấy A · M · B **có vạch bằng nhau ở hai nửa**;
--     hình tròn phải có tâm O và hai đầu đường kính ghi B, C; góc phải có chữ A ở đỉnh và
--     B, C ở hai đầu cạnh.
--   • Lớp 4 (g4-c2-l5) góc nhọn: phải có chữ O ở đỉnh và A, B ở hai đầu cạnh.
--   • Lớp 5 (g5-c3-l3, l4) hình tròn: phải ghi "bán kính r" và "đường kính d" — đúng chữ
--     mà công thức dùng.
--   • Lớp 5 hình KHỐI (g5-c3-l6, g5-c3-l7, g5-c3-l8, g5-c3-l12, g5-c5-l4): cạnh khối phải
--     ghi CHỮ a, b, c cho khớp công thức dùng chữ — "Sxq = (a + b) × 2 × c",
--     "V = a × b × c", "V = a × a × a". Quy ước: a = cạnh dài dưới cùng, b = cạnh rộng
--     (nghiêng, bên phải), c = cạnh cao (đứng, bên trái). Khối lập phương ghi a ở hai cạnh
--     đứng. Duới hình vẫn có dòng số "dài 4, rộng 3, cao 2" để bé đối chiếu chữ ↔ số.
--     🔴 Nếu hình khối CHỈ có số mà không có chữ a, b, c ⇒ DÁN THIẾU `06-bai-lop-5.sql`.
